{% set name = "tuc" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/riquito/tuc/archive/v{{ version }}.tar.gz
  sha256: bb6d16772ed0728f396d32066d391206420497a4f902071b0229790a8c844307

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - tuc --help

about:
  home: https://github.com/riquito/tuc
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Text manipulation and cutting tool
  dev_url: https://github.com/riquito/tuc

extra:
  recipe-maintainers:
    - danielnachun
